# Generated by Django 2.1 on 2018-08-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
