# Generated by Django 2.1 on 2018-08-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
