# Generated by Django 2.1 on 2018-08-14 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sal', '0002_servicearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sal.Provider'),
            preserve_default=False,
        ),
    ]
