# Generated by Django 2.1 on 2018-08-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sal', '0005_auto_20180814_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='polygon',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='x1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='x2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='y1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='y2',
            field=models.FloatField(),
        ),
    ]
